name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  RunMake:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: Build program
        run: |
          make build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-program
          path: text_processor

  RunTest:
    needs: RunMake
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built program
        uses: actions/download-artifact@v4
        with:
          name: built-program
          path: .

      - name: Run functional test
        run: |
          chmod +x text_processor
          echo "Small big largest." | ./text_processor > result.txt
          # Проверка логики 17-го варианта (средняя длина 5, остаются "Small" и "largest")
          grep -q "Small" result.txt && grep -q "largest" result.txt && echo "Test Passed"

  RunPackage:
    needs: RunTest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: built-program
          path: .

      - name: Build .deb package
        run: |
          # Создаем структуру под пакет
          mkdir -p package/usr/bin
          mkdir -p package/DEBIAN
          cp text_processor package/usr/bin/
          cp control package/DEBIAN/
          # Собираем пакет с именем под твой 17 вариант
          dpkg-deb --build package text-processor-v17.deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: text-processor-v17.deb
          retention-days: 1

  test-docker:
    needs: RunPackage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download deb package
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: .

      - name: Build Docker image
        run: docker build -t myapp-test .

      - name: Save Docker image to dist folder
        run: |
          mkdir -p dist
          docker save myapp-test:latest -o dist/myapp-container.tar
          gzip -f dist/myapp-container.tar
          echo "Локальный артефакт контейнера создан:"
          ls -la dist/

      - name: Upload container artifact to dist
        uses: actions/upload-artifact@v4
        with:
          name: container-image
          path: dist/myapp-container.tar.gz
          retention-days: 1